name: oxfmt ecosystem ci

on:
  schedule:
    - cron: "30 1,7,13,19 * * *" # Every 6 hours, gaps in the oxlint-ci
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:
    inputs: # for create comment action https://github.com/peter-evans/create-or-update-comment?tab=readme-ov-file#action-inputs
      issue-number:
        required: false
        type: string
      comment-id:
        required: false
        type: string
      ref:
        required: false
        type: string
        default: "main"

jobs:
  reply:
    name: Reply
    if: ${{ inputs.issue-number && inputs.comment-id }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          repository: oxc-project/oxc
          issue-number: ${{ inputs.issue-number }}
          comment-id: ${{ inputs.comment-id }}
          reactions: eyes

  build:
    name: Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: oxc-project/oxc
          ref: ${{ inputs.ref }}
          persist-credentials: false
          show-progress: false

      - uses: oxc-project/setup-rust@c8224157c0bf235aabc633e8cd50d344f087a7de # v1.0.12
        with:
          save-cache: ${{ github.ref_name == 'main' }}

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

      - run: pnpm install

      # Equivalent to `pnpm build` with `detect_code_removal` feature
      - run: pnpm --filter ./apps/oxfmt run build-napi --release --features allocator,detect_code_removal
        env:
          RUSTFLAGS: "-C debug-assertions=true"
      - run: pnpm --filter ./apps/oxfmt run build-js

      # `pnpm pack` does not work for `apps/oxfmt` because:
      # - `.node` is ignored, not being packed
      # - Also, `bin` field does not exist
      # Instead, using `npm/oxfmt` for global CLI install
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          if-no-files-found: error
          name: oxfmt
          path: |
            ./apps/oxfmt/dist
            ./npm/oxfmt/package.json
            ./npm/oxfmt/bin

  checkout:
    name: Read oxfmt-matrix.json
    needs: build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.content }}
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - id: setmatrix
        uses: jaywcjlove/github-action-read-file@d7632d78b76cbfbe8841dc31dd08dd2020175c80 # main
        with:
          localfile: ./oxfmt-matrix.json

  test:
    needs: checkout
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.checkout.outputs.matrix) }}
    name: Test ${{ matrix.repository }}
    steps:
      - name: Clone ${{ matrix.repository }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: ${{ matrix.repository }}
          ref: ${{ matrix.ref }}
          path: ${{ matrix.path }}
          persist-credentials: false
          show-progress: false

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: oxfmt
          path: oxfmt-package

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: 24

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 10

      - name: Install oxfmt globally
        run: |
          # Create package structure
          # ```
          # oxfmt-install
          # |- package.json
          # |- bin/oxfmt
          # |- dist/cli.js, *.node, etc
          # ```
          mkdir -p oxfmt-install
          cp oxfmt-package/npm/oxfmt/package.json oxfmt-install/
          cp -r oxfmt-package/npm/oxfmt/bin oxfmt-install/
          cp -r oxfmt-package/apps/oxfmt/dist oxfmt-install/
          # Dependencies are not installed automatically by this way
          cd oxfmt-install && npm install
          cd ..
          # Install globally
          npm install -g ./oxfmt-install

      - name: Run oxfmt
        working-directory: ${{ matrix.path }}
        run: ${{ matrix.command }}

      - name: Check diff
        working-directory: ${{ matrix.path }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not properly formatted. See the diff below:";
            git --no-pager diff;
            exit 1;
          else
            echo "Code is properly formatted.";
          fi

  comment:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Reply Comment
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        id: script
        if: ${{ inputs.issue-number }}
        with:
          github-token: ${{ secrets.OXC_BOT_PAT }}
          result-encoding: string
          script: |
            const {
              data: { jobs },
            } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              per_page: 100,
            });
            let result = jobs
              .filter((job) => job.name.startsWith("Test "))
              .map((job) => {
                const suite = job.name.slice(5);
                return { suite, conclusion: job.conclusion, link: job.html_url };
              });
            const url = `${context.serverUrl}//${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const urlLink = `[Open](${url})`;
            const conclusionEmoji = {
              success: ":white_check_mark:",
              failure: ":x:",
              cancelled: ":stop_button:",
            };
            const body = `
            ## [Oxfmt Ecosystem CI](${urlLink})
            | suite | result |
            |-------|--------|
            ${result.map((r) => `| [${r.suite}](${r.link}) | ${conclusionEmoji[r.conclusion]} |`).join("\n")}
            `;
            return body;

      - uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        if: ${{ inputs.issue-number && inputs.comment-id }}
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          repository: oxc-project/oxc
          issue-number: ${{ inputs.issue-number }}
          comment-id: ${{ inputs.comment-id }}
          body: ${{ steps.script.outputs.result }}
          edit-mode: replace
